/* This is code generated by @frourio/next. Do not edit directly. */
import { NextRequest, NextResponse } from 'next/server';
import type { z } from 'zod';
import { frourioSpec } from './frourio';
import type { GET, POST } from './route';

type RouteChecker = [typeof GET, typeof POST];

type SpecType = typeof frourioSpec;

type Controller = {
  get: (
    req: {
      headers: z.infer<SpecType['get']['headers']>;
    },
  ) => Promise<NextResponse | Response>;
  post: (
    req: {
      headers: z.infer<SpecType['post']['headers']>;
    },
  ) => Promise<NextResponse | Response>;
};

type MethodHandler = (req: NextRequest | Request) => Promise<NextResponse>;

type ResHandler = {
  GET: MethodHandler
  POST: MethodHandler
};

export const createRoute = (controller: Controller): ResHandler => {
  return {
    GET: async (req) => {
      const headers = frourioSpec.get.headers.safeParse(Object.fromEntries(req.headers));

      if (headers.error) return createReqErr(headers.error);

      const res = await controller.get({ headers: headers.data });

      return res instanceof NextResponse ? res : new NextResponse(res.body, res);
    },
    POST: async (req) => {
      const headers = frourioSpec.post.headers.safeParse(Object.fromEntries(req.headers));

      if (headers.error) return createReqErr(headers.error);

      const res = await controller.post({ headers: headers.data });

      return res instanceof NextResponse ? res : new NextResponse(res.body, res);
    },
  };
};

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );

const createResErr = () =>
  NextResponse.json<FrourioError>(
    { status: 500, error: 'Internal Server Error' },
    { status: 500 },
  );
